sunshine_name = Streamy Boy
sw_preset = fast
nvenc_preset = 1
capture = kwin
output_name = Virtual-sunshine-vm
global_prep_cmd = [{"do":"/home/shrinksenpai/.config/sunshine/hooks/stream-start.sh","undo":"/home/shrinksenpai/.config/sunshine/hooks/stream-end.sh","elevated":"false"}]
